package com.flydubai.hellosoap;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 4.0.3
 * 2024-03-05T14:09:21.970+05:30
 * Generated source version: 4.0.3
 *
 */
@WebService(targetNamespace = "http://www.flydubai.com/HelloSoap", name = "ClientPort")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface ClientPort {

    @WebMethod(operationName = "HelloSoap")
    @WebResult(name = "HelloSoapResponse", targetNamespace = "http://www.flydubai.com/HelloSoap", partName = "HelloSoapResponse")
    public HelloSoapResponse helloSoap(

        @WebParam(partName = "HelloSoapRequest", name = "HelloSoapRequest", targetNamespace = "http://www.flydubai.com/HelloSoap")
        HelloSoapRequest helloSoapRequest
    );
}
