package com.flydubai.hellosoap;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceFeature;
import jakarta.xml.ws.Service;

/**
 * This class was generated by Apache CXF 4.0.3
 * 2024-03-05T14:09:22.026+05:30
 * Generated source version: 4.0.3
 *
 */
@WebServiceClient(name = "ClientPortService",
                  wsdlLocation = "file:/C:/Users/ashisht/Desktop/Eclipse-Workspaces/PersonalWorkspace/quarkus-grpc-soap/src/main/resources/helloSoapService.wsdl",
                  targetNamespace = "http://www.flydubai.com/HelloSoap")
public class ClientPortService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.flydubai.com/HelloSoap", "ClientPortService");
    public final static QName ClientPortSoap11 = new QName("http://www.flydubai.com/HelloSoap", "ClientPortSoap11");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/Users/ashisht/Desktop/Eclipse-Workspaces/PersonalWorkspace/quarkus-grpc-soap/src/main/resources/helloSoapService.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(ClientPortService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "file:/C:/Users/ashisht/Desktop/Eclipse-Workspaces/PersonalWorkspace/quarkus-grpc-soap/src/main/resources/helloSoapService.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public ClientPortService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ClientPortService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ClientPortService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public ClientPortService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public ClientPortService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public ClientPortService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns ClientPort
     */
    @WebEndpoint(name = "ClientPortSoap11")
    public ClientPort getClientPortSoap11() {
        return super.getPort(ClientPortSoap11, ClientPort.class);
    }

    /**
     *
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ClientPort
     */
    @WebEndpoint(name = "ClientPortSoap11")
    public ClientPort getClientPortSoap11(WebServiceFeature... features) {
        return super.getPort(ClientPortSoap11, ClientPort.class, features);
    }

}
